
<!-- menu.inc -->
  <div class="menu">
    <table>
      <tr>
        <td class="left">
          <span class="go_xxx"><a href="%cgi_file%">new collection</a></span>
          ||
          <span class="form"><strong><TMPL_UNLESS name="summary">input form<TMPL_ELSE>summary</TMPL_UNLESS></strong></span>
        </td>
        <td class="right">
          <span class="go_xxx"><a href="%help_file%">help</a></span>
          |
          <span class="go_xxx"><a href="%home_file%">lir home</a></span>
        </td>
      </tr>
    </table>
  </div> <!-- class="menu" -->
<!-- /menu.inc/ -->
