
<!-- menu.inc -->
  <div class="menu">
    <table>
      <tr>
        <td class="left">
          <span class="go_xxx"><a href="%cgi_file%">New collection</a></span>
          <span class="divider">|</span>
          <span class="form"><strong><TMPL_UNLESS name="summary">Input form<TMPL_ELSE>Summary</TMPL_UNLESS></strong></span>
        </td>
        <td class="right">
          <!--
          <span class="go_xxx"><a href="%help_file%">Help</a></span>
          <span class="divider">|</span>
          -->
          <span class="go_xxx"><a href="%home_file%">LIR home</a></span>
        </td>
      </tr>
    </table>
  </div> <!-- class="menu" -->
<!-- /menu.inc/ -->
